#:schema node_modules/wrangler/config-schema.json
name = "bskye"
main = "src/index.ts"
minify = true
compatibility_date = "2025-12-17"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true
